### ISSUE TITLE
Proposal: Support multiple config files

### ISSUE THREAD

**Issue by rustysys-dev** [omallassi/adrust#43]
I was thinking today about team use cases for adrust, and in particular having multiple projects for which you are writing adrs for.

to support this usecase, I propose a configuration profile manager.  Since the configuration file is written in TOML, this manager could support the following.

- create named profiles
- current/default profile 
- import other config files  (you could save a config file in git repository and share it)

to express this visually I have the following examples:

to create the config for the first example:
```bash
adr config new --name profile1              # create a new profile with default values
adr config default --name profile1          # set profile1 as default configuration profile
adr config set --name log_level --value 4   # set parameter value as currently done.
...
adr config new --name profile2
adr config set --name log_level --value 4 --profile profile2
...
```

example config 1:

```toml
default = "profile1"

[profile1]
log_level = 4
adr_src_dir = '/tmp/adr-samples/src'
adr_template_dir = '/tmp/adr-samples/templates'
adr_template_file = 'adr-template-v0.1.adoc'
adr_search_index = '/tmp/adr-samples/.index'
use_id_prefix = true
id_prefix_width = 6

[profile2]
log_level = 4
adr_src_dir = '/tmp/adr-samples/src'
adr_template_dir = '/tmp/adr-samples/templates'
adr_template_file = 'adr-template-v0.1.adoc'
adr_search_index = '/tmp/adr-samples/.index'
use_id_prefix = true
id_prefix_width = 6
```

to create the config for the second example:

```bash
adr config new --name profile1 --from /path/to/config/file.toml
adr config new --name profile2 --from /path/to/second/config/file.toml
adr config default --name profile2
```

example config 2:

```toml
default = "profile2"

[profile1]
config_source = '/path/to/config/file.toml'

[profile2]
config_source = '/path/to/second/config/file.toml'
```

or you could mix and match the styles:

```bash
adr config new --name profile1              # create a new profile with default values
adr config default --name profile1          # set profile1 as default configuration profile
adr config set --name log_level --value 4   # set parameter value as currently done.
...
adr config new --name profile2 --from /path/to/second/config/file.toml
```

example config 3:

```toml
default = "profile1"

[profile1]
log_level = 4
adr_src_dir = '/tmp/adr-samples/src'
adr_template_dir = '/tmp/adr-samples/templates'
adr_template_file = 'adr-template-v0.1.adoc'
adr_search_index = '/tmp/adr-samples/.index'
use_id_prefix = true
id_prefix_width = 6

[profile2]
config_source = '/path/to/second/config/file.toml'
```
